name: Update Montreal COVID-19 Data
env:
  MONTREAL_DATA_URL: https://santemontreal.qc.ca/fileadmin/fichiers/Campagnes/coronavirus/situation-montreal/courbe.csv
  OUTPUT_LOCATION: city/CA/CA_MTR.csv
  CHROME_UA: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '38 0,6,12,18 * * *'
jobs:
  latest-montreal-data:
    name: "Get latest Montreal data"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: "Download Montreal CSV file"
        run: "curl -A ${CHROME_UA} -o ${OUTPUT_LOCATION} ${MONTREAL_DATA_URL}"
      - name: "Commit Montreal data file"
        uses: test-room-7/action-update-file@v1
        with:
            file-path: ${{ env.OUTPUT_LOCATION }}
            commit-msg: "Automated update of Montreal data file"
            github-token: ${{ secrets.MY_GITHUB_TOKEN }}
    
